Update and rename sca.yml to SCA.yml
re-scan1

diff --git a/.github/workflows/SCA.yml b/.github/workflows/SCA.yml
--- a/.github/workflows/SCA.yml
+++ b/.github/workflows/SCA.yml
@@ -1,14 +1,28 @@
-name: SCA Check and Gradle Build
+name: SAST Check and Gradle Build
 on:
   push:
-    branches: [ main ]
+    branches: [ master ]
   pull_request:
-    branches: [ main ]
+    branches: [ master ]
 jobs:
-  sca-and-build:
+  sast-and-build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
+    - name: List repository contents
+      run: ls -R
+    - name: Check Gradle Wrapper files
+      run: |
+        if [ -f "gradlew" ] && [ -f "gradlew.bat" ] && [ -d "gradle/wrapper" ]; then
+          echo "Gradle Wrapper files found."
+        else
+          echo "Gradle Wrapper files are missing."
+          echo "Contents of the current directory:"
+          ls -la
+          echo "Contents of the gradle directory (if it exists):"
+          [ -d "gradle" ] && ls -la gradle || echo "gradle directory not found"
+          exit 1
+        fi
     - name: Validate Gradle Wrapper
       uses: gradle/wrapper-validation-action@v1
     - name: Set up JDK 11
@@ -27,32 +41,32 @@ jobs:
       run: chmod +x gradlew
     - name: Create project zip
       run: zip -r project.zip . -x "*.git*"
-    - name: Perform SCA Scan
-      id: sca
+    - name: Perform SAST Scan
+      id: sast
       run: |
         RESPONSE=$(curl -X POST \
           -H "Client-ID: ${{ secrets.INTRUCEPT_CLIENT_ID }}" \
           -H "Client-Secret: ${{ secrets.INTRUCEPT_CLIENT_SECRET }}" \
           -F "projectZipFile=@project.zip" \
           -F "applicationId=${{ secrets.INTRUCEPT_APPLICATION_ID }}" \
-          -F "scanName=c-tutorial-master-SCA Re-Scan1 - Gradle - from GitHub Actions" \
+          -F "scanName=SAST re-Scan1 - Gradle - from GitHub Actions" \
           -F "language=java" \
-          https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)
+          https://appsecops-api.intruceptlabs.com/api/v1/integrations/sast-scans)
         
-        echo "SCA Response:"
+        echo "SAST Response:"
         VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
         if [ "$VULNS_TABLE" != "null" ] && [ -n "$VULNS_TABLE" ]; then
           echo "$VULNS_TABLE"
         else
-          echo "No SCA vulnerabilities found"
+          echo "No SAST vulnerabilities found"
         fi
         
         CAN_PROCEED=$(echo $RESPONSE | jq -r '.canProceed')
         echo "canProceed=$CAN_PROCEED" >> $GITHUB_ENV
-    - name: Check SCA result
+    - name: Check SAST result
       if: env.canProceed != 'true'
       run: |
-        echo "SCA scan failed. Build cancelled."
+        echo "SAST scan failed. Build cancelled."
         exit 1
     - name: Build with Gradle
       if: env.canProceed == 'true'
